### ISSUE TITLE
How does this plugin work with merge commits?

### ISSUE THREAD

**Issue by ivan-osipov** [NetrisTV/gradle-commitlint-plugin#1]
Hi, thanks for the plugin

I tried the plugin but faced with the following problem
If I do merge from master to my feature branch (to sync its state with the latest state) and at the same time I validate the commit message then I get an error because a default merge commit message follows the pattern: "Merge <branch1> into <branch2> ". Do you have any recommendations, what is the best way to solve the conflict?

Upd:
I found [the following thread](https://www.google.com/url?sa=t&source=web&rct=j&url=https://github.com/conventional-changelog/commitlint/issues/365&ved=2ahUKEwiZtrbNk9jsAhVFx4sKHakJCm0QFjAAegQIJBAC&usg=AOvVaw0OvsDpxSre-yFPFOFFYYLm ) in commitlint github, so do we have to upgrade commitlint under the hood?

**Comment by prop** [comment]
Hi.

Thanks for the issue.
I backported ignoring some messages (github/gitlab merge commits etc) from `@commitlint/is-ignored` npm package.
Please update this plugin to `1.3`
