### ISSUE TITLE
Comment lines count toward 50/72 rule

### ISSUE THREAD

**Issue by ricardocosta** [NetrisTV/gradle-commitlint-plugin#2]
When validating the commit message, this plugin checks the entire message, including the comment lines (starting with `#`). Despite not being part of the commit, if a comment line goes over the 72 characters limit, the plugin will not let the commit go through.

A solution proposal is to change the fetching of `lines` to also filter out the lines starting with `#`.
https://github.com/NetrisTV/gradle-commitlint-plugin/blob/4d3fd160ec6d04ffbccd35ab25b2b892651e189a/src/main/groovy/ru/netris/commitlint/CommitlintUtil.groovy#L69

```
def lines = msg.split("\n").findAll { !it.startsWith("#") }
```

**Comment by prop** [comment]
@ricardocosta thanks for the report. Implemented in 1.4
