### ISSUE TITLE
Bug in regex for git's fixup

### ISSUE THREAD

**Issue by ricardocosta** [NetrisTV/gradle-commitlint-plugin#3]
The `shouldBeIgnored` function is requiring an exact match by using the `==~` operator.

However, when using `git commit --fixup=<hash>` the resulting commit message becomes, as an example, `fixup! feat: Add example POST endpoint`.

The Regex for `fixup` or `squash` is `~/^(fixup|squash)!/`, which will not match the generated commit message.

I believe the same wildcard as of the other Regex is needed ` (.*)`, so it should be `~/^(fixup|squash)! (.*)/`.

**Comment by prop** [comment]
Thanks.
FIxed in `1.4.1`
